In [3]:
# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Load the data
fct = pd.read_csv('FCT-ABDUCTION.csv', encoding='latin-1')

# Check size
print(f"Rows: {fct.shape[0]}, Columns: {fct.shape[1]}")

# Check column names
print(fct.columns.tolist())

# Check data types
print(fct.dtypes)

# First few rows
fct.head()

Rows: 167, Columns: 14
['DATE', 'THREAT ACTORS', 'AFFAECTED GROUOS', 'SECURITY INCIDENT TYPE', 'SECURITY INCIDENT SUB-TYPE', 'STATE', 'LAC', 'LOCATION', 'NUMBER OF PEOPLE KIDNAPPED', 'NUMBER OF PEOPLE KILLED', 'NUMBER OF PEOPLE INJURED', 'BREAKDOWN OF INCIDENT', 'MONTH', 'YEAR']
DATE                           object
THREAT ACTORS                  object
AFFAECTED GROUOS               object
SECURITY INCIDENT TYPE         object
SECURITY INCIDENT SUB-TYPE     object
STATE                          object
LAC                            object
LOCATION                       object
NUMBER OF PEOPLE KIDNAPPED    float64
NUMBER OF PEOPLE KILLED       float64
NUMBER OF PEOPLE INJURED      float64
BREAKDOWN OF INCIDENT          object
MONTH                          object
YEAR                            int64
dtype: object

,DATE,THREAT ACTORS,AFFAECTED GROUOS,SECURITY INCIDENT TYPE,SECURITY INCIDENT SUB-TYPE,STATE,LAC,LOCATION,NUMBER OF PEOPLE KIDNAPPED,NUMBER OF PEOPLE KILLED,NUMBER OF PEOPLE INJURED,BREAKDOWN OF INCIDENT,MONTH,YEAR
0,1/23/2021,Criminals,Civilians,Abduction,Kidnapping,Federal Capital Territory,Abaji,Other,8.0,0.0,0.0,"Gunmen attack orphanage home, abduct 10 in Abuja",Jan,2021
1,2/2/2021,Criminals,Civilians,Abduction,Kidnapping,Federal Capital Territory,Bwari,Residence,3.0,0.0,0.0,"Gunmen kidnap father of Council chair, 2 sibli...",Feb,2021
2,2/26/2021,Criminals,Civilians,Abduction,Kidnapping,Federal Capital Territory,Bwari,Residence,2.0,0.0,0.0,"Anxiety as gunmen invade Abuja community, abdu...",Feb,2021
3,3/14/2021,Criminals,Civilians,Abduction,Kidnapping,Federal Capital Territory,Abaji,Community,4.0,0.0,0.0,Two killed as police foil kidnap attempt in Ab...,Mar,2021
4,3/24/2021,Criminals,Civilians,Abduction,Kidnapping,Federal Capital Territory,Kuje,Residence,4.0,0.0,0.0,"Gunmen abduct 4 persons in Abuja, demand N200m...",Mar,2021

In [4]:
# Check for missing values
fct.isnull().sum()

DATE                          0
THREAT ACTORS                 1
AFFAECTED GROUOS              1
SECURITY INCIDENT TYPE        1
SECURITY INCIDENT SUB-TYPE    1
STATE                         1
LAC                           1
LOCATION                      1
NUMBER OF PEOPLE KIDNAPPED    1
NUMBER OF PEOPLE KILLED       1
NUMBER OF PEOPLE INJURED      1
BREAKDOWN OF INCIDENT         1
MONTH                         1
YEAR                          0
dtype: int64

In [5]:
# Look at the last 3 rows
fct.tail(3)

,DATE,THREAT ACTORS,AFFAECTED GROUOS,SECURITY INCIDENT TYPE,SECURITY INCIDENT SUB-TYPE,STATE,LAC,LOCATION,NUMBER OF PEOPLE KIDNAPPED,NUMBER OF PEOPLE KILLED,NUMBER OF PEOPLE INJURED,BREAKDOWN OF INCIDENT,MONTH,YEAR
164,11/26/2025,Criminals,Civilians,Abduction,Kidnapping,Federal Capital Territory,Bwari,Community,7.0,0.0,0.0,"Bandits abduct teenage boy, six girls from FCT...",Nov,2025
165,12/5/2025,Bandits,Civilians,Abduction,Kidnapping,Federal Capital Territory,Bwari,Other,5.0,0.0,0.0,A joint team of the Nigeria Police Force (FCT ...,Dec,2025
166,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335815

In [6]:
# Drop the last row
fct = fct.drop(fct.index[-1])

# Confirm removal
fct.tail()

,DATE,THREAT ACTORS,AFFAECTED GROUOS,SECURITY INCIDENT TYPE,SECURITY INCIDENT SUB-TYPE,STATE,LAC,LOCATION,NUMBER OF PEOPLE KIDNAPPED,NUMBER OF PEOPLE KILLED,NUMBER OF PEOPLE INJURED,BREAKDOWN OF INCIDENT,MONTH,YEAR
161,10/2/2025,Criminals,Civilians,Abduction,Abduction,Federal Capital Territory,Bwari,Other,3.0,1.0,0.0,Credible reports indicate that suspected armed...,Oct,2025
162,10/1/2025,NSAG - Non State Armed Group,Civilians,Abduction,Abduction,Federal Capital Territory,Bwari,Community,4.0,0.0,0.0,"Gunmen kidnap vet doctor, three children in Ab...",Oct,2025
163,10/21/2025,Criminals,Civilians,Abduction,Kidnapping,Federal Capital Territory,Abuja Municipal,Other,1.0,0.0,0.0,Man abducted from Abuja found dead in Kaduna,Oct,2025
164,11/26/2025,Criminals,Civilians,Abduction,Kidnapping,Federal Capital Territory,Bwari,Community,7.0,0.0,0.0,"Bandits abduct teenage boy, six girls from FCT...",Nov,2025
165,12/5/2025,Bandits,Civilians,Abduction,Kidnapping,Federal Capital Territory,Bwari,Other,5.0,0.0,0.0,A joint team of the Nigeria Police Force (FCT ...,Dec,2025

In [7]:
# Recheck for missing values
fct.isnull().sum()

DATE                          0
THREAT ACTORS                 0
AFFAECTED GROUOS              0
SECURITY INCIDENT TYPE        0
SECURITY INCIDENT SUB-TYPE    0
STATE                         0
LAC                           0
LOCATION                      0
NUMBER OF PEOPLE KIDNAPPED    0
NUMBER OF PEOPLE KILLED       0
NUMBER OF PEOPLE INJURED      0
BREAKDOWN OF INCIDENT         0
MONTH                         0
YEAR                          0
dtype: int64

In [8]:
# Check for duplicates
print(f"Number of duplicate rows: {fct.duplicated().sum()}")

Number of duplicate rows: 2

In [9]:
# Show the duplicate rows so you can see what they are
fct[fct.duplicated(keep=False)]

,DATE,THREAT ACTORS,AFFAECTED GROUOS,SECURITY INCIDENT TYPE,SECURITY INCIDENT SUB-TYPE,STATE,LAC,LOCATION,NUMBER OF PEOPLE KIDNAPPED,NUMBER OF PEOPLE KILLED,NUMBER OF PEOPLE INJURED,BREAKDOWN OF INCIDENT,MONTH,YEAR
87,9/16/2023,Criminals,Civilians,Abduction,Kidnapping,Federal Capital Territory,Abuja Municipal,Residence,0.0,0.0,1.0,Abuja man escapes kidnap attempt by fake soldiers,Sep,2023
90,10/3/2023,NSAG - Non State Armed Group,Civilians,Abduction,Kidnapping,Federal Capital Territory,Gwagwalada,School,0.0,0.0,0.0,Gunmen Attempt To Abduct Female Student From U...,Oct,2023
98,9/16/2023,Criminals,Civilians,Abduction,Kidnapping,Federal Capital Territory,Abuja Municipal,Residence,0.0,0.0,1.0,Abuja man escapes kidnap attempt by fake soldiers,Sep,2023
99,10/3/2023,NSAG - Non State Armed Group,Civilians,Abduction,Kidnapping,Federal Capital Territory,Gwagwalada,School,0.0,0.0,0.0,Gunmen Attempt To Abduct Female Student From U...,Oct,2023

In [10]:
# Remove duplicates, keeping the first occurrence
fct = fct.drop_duplicates()

In [11]:
# Check duplicate count again
print(f"Remaining duplicates: {fct.duplicated().sum()}")

Remaining duplicates: 0

In [12]:
# Convert to datetime
fct['DATE'] = pd.to_datetime(fct['DATE'])

# Now you can extract useful components
fct['YEAR'] = fct['DATE'].dt.year
fct['MONTH'] = fct['DATE'].dt.month
fct['DAY'] = fct['DATE'].dt.day
fct['DAY_OF_WEEK'] = fct['DATE'].dt.day_name()

In [13]:
# Check the data types
print(fct[['NUMBER OF PEOPLE KIDNAPPED', 'NUMBER OF PEOPLE KILLED', 'NUMBER OF PEOPLE INJURED']].dtypes)

# Check for any negative values or impossibly large values
print(fct[['NUMBER OF PEOPLE KIDNAPPED', 'NUMBER OF PEOPLE KILLED', 'NUMBER OF PEOPLE INJURED']].describe())

NUMBER OF PEOPLE KIDNAPPED    float64
NUMBER OF PEOPLE KILLED       float64
NUMBER OF PEOPLE INJURED      float64
dtype: object
       NUMBER OF PEOPLE KIDNAPPED  NUMBER OF PEOPLE KILLED  \
count                  164.000000               164.000000
mean                     4.378049                 0.207317
std                      5.480899                 0.501233
min                      0.000000                 0.000000
25%                      1.000000                 0.000000
50%                      2.000000                 0.000000
75%                      5.000000                 0.000000
max                     29.000000                 3.000000

       NUMBER OF PEOPLE INJURED
count                164.000000
mean                   0.115854
std                    0.448575
min                    0.000000
25%                    0.000000
50%                    0.000000
75%                    0.000000
max                    3.000000

In [14]:
# Check unique LGA values
fct['LAC'].unique()

array(['Abaji', 'Bwari', 'Kuje', 'Gwagwalada', 'Kwali', 'Abuja Municipal',
       'Karu'], dtype=object)

In [15]:
# Check unique threat actor values
fct['THREAT ACTORS'].unique()

array(['Criminals', 'NSAG - Non State Armed Group', 'Civilians',
       'Security Forces (Military, Police, Paramilitary, DSS / SSS and including MNJTF)',
       'Unknown', 'Political Thug/Hired Assailant', 'Bandits',
       'Humanitarian Aid Worker'], dtype=object)

In [16]:
# Standardize threat actor categories (shorten long names only)
fct['THREAT ACTORS'] = fct['THREAT ACTORS'].replace({
    'NSAG - Non State Armed Group': 'NSAG',
    'Security Forces (Military, Police, Paramilitary, DSS / SSS and including MNJTF)': 'Security Forces',
    'Political Thug/Hired Assailant': 'Political Thug'
})

In [17]:
fct['THREAT ACTORS'].value_counts()

THREAT ACTORS
Criminals                  106
NSAG                        39
Bandits                     11
Civilians                    3
Unknown                      2
Security Forces              1
Political Thug               1
Humanitarian Aid Worker      1
Name: count, dtype: int64

In [18]:
# Show all column names
fct.columns.tolist()

['DATE',
 'THREAT ACTORS',
 'AFFAECTED GROUOS',
 'SECURITY INCIDENT TYPE',
 'SECURITY INCIDENT SUB-TYPE',
 'STATE',
 'LAC',
 'LOCATION',
 'NUMBER OF PEOPLE KIDNAPPED',
 'NUMBER OF PEOPLE KILLED',
 'NUMBER OF PEOPLE INJURED',
 'BREAKDOWN OF INCIDENT',
 'MONTH',
 'YEAR',
 'DAY',
 'DAY_OF_WEEK']

In [19]:
# Rename the column
fct.rename(columns={'AFFAECTED GROUOS': 'AFFECTED GROUPS'}, inplace=True)

# Verify the change
print(fct.columns.tolist())

['DATE', 'THREAT ACTORS', 'AFFECTED GROUPS', 'SECURITY INCIDENT TYPE', 'SECURITY INCIDENT SUB-TYPE', 'STATE', 'LAC', 'LOCATION', 'NUMBER OF PEOPLE KIDNAPPED', 'NUMBER OF PEOPLE KILLED', 'NUMBER OF PEOPLE INJURED', 'BREAKDOWN OF INCIDENT', 'MONTH', 'YEAR', 'DAY', 'DAY_OF_WEEK']

In [20]:
# Check rows where THREAT ACTORS is 'Civilians'
fct[fct['THREAT ACTORS'] == 'Civilians'][['THREAT ACTORS', 'AFFECTED GROUPS', 'BREAKDOWN OF INCIDENT']]

,THREAT ACTORS,AFFECTED GROUPS,BREAKDOWN OF INCIDENT
28,Civilians,Civilians,"5 year old girl goes missing in Karu, Abuja."
72,Civilians,Civilians,New tenants flee with neighbours two children...
124,Civilians,Civilians,"Abuja chef allegedly kidnaps boss son, collec..."

In [21]:
# Incidents by year
fct['YEAR'].value_counts().sort_index()

YEAR
2021    21
2022    38
2023    48
2024    37
2025    20
Name: count, dtype: int64

In [22]:
# Incidents by LGA
fct['LAC'].value_counts()

LAC
Abuja Municipal    53
Bwari              49
Kuje               20
Kwali              18
Abaji              17
Gwagwalada          6
Karu                1
Name: count, dtype: int64

In [23]:
# Threat actor distribution
fct['THREAT ACTORS'].value_counts()

THREAT ACTORS
Criminals                  106
NSAG                        39
Bandits                     11
Civilians                    3
Unknown                      2
Security Forces              1
Political Thug               1
Humanitarian Aid Worker      1
Name: count, dtype: int64

In [24]:
# Check if 2025 is complete
fct[fct['YEAR'] == 2025]['MONTH'].value_counts().sort_index()

MONTH
1     2
2     4
3     2
5     2
6     1
7     2
8     1
9     1
10    3
11    1
12    1
Name: count, dtype: int64

In [25]:
# Total kidnapped by LGA
fct.groupby('LAC')['NUMBER OF PEOPLE KIDNAPPED'].sum().sort_values(ascending=False)

LAC
Bwari              265.0
Abuja Municipal    166.0
Kuje               113.0
Kwali               78.0
Abaji               77.0
Gwagwalada          18.0
Karu                 1.0
Name: NUMBER OF PEOPLE KIDNAPPED, dtype: float64

In [26]:
# Incidents by month (all years combined)
fct['MONTH'].value_counts().sort_index()

MONTH
1     21
2     15
3     15
4     13
5     12
6     13
7     17
8      9
9     15
10    11
11     9
12    14
Name: count, dtype: int64

In [27]:
# Average killed by threat actor
fct.groupby('THREAT ACTORS')['NUMBER OF PEOPLE KILLED'].mean().sort_values(ascending=False)

THREAT ACTORS
Political Thug             1.000000
Unknown                    1.000000
Bandits                    0.636364
Criminals                  0.179245
NSAG                       0.128205
Civilians                  0.000000
Humanitarian Aid Worker    0.000000
Security Forces            0.000000
Name: NUMBER OF PEOPLE KILLED, dtype: float64

In [28]:
# Scatter plot or correlation
fct[['NUMBER OF PEOPLE KIDNAPPED', 'NUMBER OF PEOPLE KILLED']].corr()

,NUMBER OF PEOPLE KIDNAPPED,NUMBER OF PEOPLE KILLED
NUMBER OF PEOPLE KIDNAPPED,1.000000,0.100819
NUMBER OF PEOPLE KILLED,0.100819,1.000000

In [29]:
# Check for ransom mentions
fct[fct['BREAKDOWN OF INCIDENT'].str.contains('ransom', case=False, na=False)][['BREAKDOWN OF INCIDENT', 'THREAT ACTORS']].head(10)

                                 BREAKDOWN OF INCIDENT THREAT ACTORS
4    Gunmen abduct 4 persons in Abuja, demand N200m...     Criminals
100  Gunmen kidnap Abuja landlords, demand N20m ransom     Criminals
101  Gunmen kidnap Abuja landlords, demand N20m ransom     Criminals
124  Abuja chef allegedly kidnaps boss son, collec...     Civilians

In [30]:
# Check for deaths
fct[fct['NUMBER OF PEOPLE KILLED'] > 0][['BREAKDOWN OF INCIDENT', 'NUMBER OF PEOPLE KILLED', 'THREAT ACTORS']].head(10)

,BREAKDOWN OF INCIDENT,NUMBER OF PEOPLE KILLED,THREAT ACTORS
20,"Gunmen abduct DSS official, kills vigilante me...",1.0,Criminals
22,Gunmen kill 1 man & abducts a 12 year old girl...,1.0,NSAG
23,"Gunmen kill motorcyclist, abduct Abuja monarch...",1.0,Criminals
32,"Female corp memberkidnapped in Abuja, found dead",1.0,Criminals
37,"Bandits abduct 22 farmers, kill 2 in Abaji are...",2.0,Criminals
40,"1 killed,2 injured and 10 abducted as bandits ...",1.0,Criminals
50,Nigerian government official kidnapped alongsi...,1.0,Unknown
52,Unknown armed men abduct 1 civillian and kill ...,1.0,Unknown
57,"1 injured,1 killed and 8 abducted from Arab ro...",1.0,Criminals
62,"1 man killed by gunmen, wife and cousin abduct...",1.0,Criminals

In [31]:
# Check for large-scale kidnappings (10+ people)
fct[fct['NUMBER OF PEOPLE KIDNAPPED'] >= 10][['BREAKDOWN OF INCIDENT', 'NUMBER OF PEOPLE KIDNAPPED', 'LAC']].head(10)

,BREAKDOWN OF INCIDENT,NUMBER OF PEOPLE KIDNAPPED,LAC
35,"3 pregnant women,2 children and 12 others abdu...",17.0,Abuja Municipal
36,Alledged kiddnappers in army uniform pick 17 p...,17.0,Abuja Municipal
37,"Bandits abduct 22 farmers, kill 2 in Abaji are...",22.0,Abaji
40,"1 killed,2 injured and 10 abducted as bandits ...",10.0,Abaji
45,1 Army captain and 13 soldiers abducted in Abuja.,14.0,Bwari
49,"AOG raid community in Abuja, kidnap 10 people.",10.0,Abaji
58,16 persons abducted by gunmen in Gwonbe commun...,16.0,Kuje
65,"Gunmen raid estate in Abuja, kidnap 11 includi...",11.0,Abuja Municipal
69,Gunmen Abduct 13 In Fct Community,13.0,Kuje
70,29 abducted from Kwali LGA of the FCT.,29.0,Kwali

In [32]:
# Check for mentions of "ransom"
fct[fct['BREAKDOWN OF INCIDENT'].str.contains('ransom', case=False, na=False)]['THREAT ACTORS'].value_counts()

THREAT ACTORS
Criminals    3
Civilians    1
Name: count, dtype: int64

In [33]:
# Check for mentions of "security" or "police"
fct[fct['BREAKDOWN OF INCIDENT'].str.contains('police|security|military|army', case=False, na=False)]['THREAT ACTORS'].value_counts()

THREAT ACTORS
Criminals          9
NSAG               3
Bandits            2
Security Forces    1
Political Thug     1
Name: count, dtype: int64

In [34]:
# Check for mentions of "school" or "student"
fct[fct['BREAKDOWN OF INCIDENT'].str.contains('school|student|teacher', case=False, na=False)][['BREAKDOWN OF INCIDENT', 'LAC']]

                                BREAKDOWN OF INCIDENT         LAC
12                   Female teacher abducted in Abuja        Kuje
34  1 injured,1 abducted as gunmen attack school o...        Kuje
90  Gunmen Attempt To Abduct Female Student From U...  Gwagwalada
92  Unkown men kidnapped 3 people a secondary scho...       Bwari

In [35]:
# Check for mentions of "women" or "children"
fct[fct['BREAKDOWN OF INCIDENT'].str.contains('woman|women|child|children', case=False, na=False)]['LAC'].value_counts()

LAC
Abuja Municipal    5
Bwari              4
Kuje               3
Kwali              2
Abaji              1
Name: count, dtype: int64

In [36]:
# Save the cleaned dataframe to CSV
fct.to_csv('fct_abduction_cleaned.csv', index=False)

print("File saved successfully!")

File saved successfully!